# Generated by Django 4.2.2 on 2023-06-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=255, unique=True, verbose_name='login')),
                ('password', models.CharField(max_length=255, verbose_name='password')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='updated_date')),
                ('is_block', models.BooleanField(default=False, verbose_name='blocked')),
            ],
        ),
        migrations.CreateModel(
            name='NarkUchet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20, unique=True, verbose_name='pin_passport')),
                ('passport_series', models.CharField(max_length=20, unique=True, verbose_name='passport_series')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='passport_number')),
            ],
        ),
        migrations.CreateModel(
            name='SertificateForCovid_19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin', models.CharField(max_length=20, unique=True, verbose_name='pin_passport')),
                ('passport_series', models.CharField(max_length=20, unique=True, verbose_name='passport_series')),
                ('passport_number', models.CharField(max_length=20, unique=True, verbose_name='passport_number')),
            ],
        ),
        migrations.CreateModel(
            name='ZapisKVrachu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, unique=True, verbose_name='client_name')),
                ('pin', models.CharField(max_length=20, unique=True, verbose_name='pin_passport')),
                ('Diagnoz', models.CharField(max_length=255, verbose_name='description_of_diagnoz')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created_date')),
            ],
        ),
    ]
