# Generated by Django 4.2.2 on 2023-06-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommunity_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zapiskvrachu',
            name='Diagnoz',
        ),
        migrations.AddField(
            model_name='zapiskvrachu',
            name='Description',
            field=models.CharField(default=6, max_length=255, verbose_name='description'),
            preserve_default=False,
        ),
    ]
