# Generated by Django 4.2.2 on 2023-06-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommunity_app', '0002_remove_zapiskvrachu_diagnoz_zapiskvrachu_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='narkuchet',
            name='Uchet',
            field=models.BooleanField(default=False, verbose_name='Nark_Uchet'),
        ),
    ]
