# Generated by Django 4.2.2 on 2023-06-17 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecommunity_app', '0003_narkuchet_uchet'),
    ]

    operations = [
        migrations.AddField(
            model_name='sertificateforcovid_19',
            name='is_exist',
            field=models.BooleanField(default=False, verbose_name='Имеетс] ли сертивикат'),
        ),
        migrations.CreateModel(
            name='PersonalCabinet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommunity_app.login')),
            ],
        ),
    ]
